# Generated by Django 3.1.3 on 2020-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
